[project]
name = "firecrawl-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "firecrawl-py>=4.3.6",
    "pydantic>=2.11.9",
]
